### ISSUE TITLE
be careful with remote services you include in CSS files

### ISSUE THREAD

**Issue by hunkjazz** [jeremyperkin/protonmail_themes#2]
ProtonMail is privacy a conscious service.

Now, when people use custom CSS themes that includes services like imgur, their privacy is compromised.

You should replace imgur and similar services with privacy conscious services.

https://prism-break.org/en/all/
https://www.privacytools.io/software/file-sharing/

**Comment by jeremyperkin** [comment]
Thanks - if you notice I stated to change that info in the code.

**Comment by hunkjazz** [comment]
Haven't noticed it, before.
